import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Motion } from "@/components/transition/motion";
import Navbar from "@/components/navbar";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({
  // weight: "400",
  subsets: ["latin"],
  // display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <NextTopLoader
            color="#006FEE"
            initialPosition={0.08}
            crawlSpeed={200}
            height={4}
            crawl={true}
            showSpinner={true}
            easing="ease"
            speed={200}
          />
          <Navbar />
          <Motion>{children}</Motion>
        </Providers>
      </body>
    </html>
  );
}
